### ISSUE TITLE
[Suggestion] Add support for room17 SkyBlocks plugin

### ISSUE THREAD

**Issue by Shelly7w7** [JackMD/ScoreHud#10]
Can you add Island size, Blocks, members of Room17 skyblock plugin?
github.com/Room17/SkyBlock

**Comment by JackMD** [comment]
Will do so later

**Comment by SkyNetServer** [comment]
yeah. That would be cool and helpful!

**Comment by JackMD** [comment]
There it is guys.. Was later but hey the feature is added.
