### ISSUE TITLE
Crash when creating a slyblock island

### ISSUE THREAD

**Issue by ManiakMCPE** [JackMD/ScoreHud#101]
This still happens with the latest version **JACK**

Error: Class 'room17\SkyBlock\session\iSession' not found
File: plugins/ScoreHud (3).phar/src/JackMD/ScoreHud/data/DataManager
Line: 359
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: ScoreHud v3.0.0

Code:
[350] 	public function getIsleRank(Player $player){
[351] 		/** @var SkyBlock $sb */
[352] 		$sb = $this->plugin->getServer()->getPluginManager()->getPlugin("SkyBlock");
[353] 		if($sb instanceof SkyBlock){
[354] 			$session = $sb->getSessionManager()->getSession($player);
[355] 			if((is_null($session)) || (!$session->hasIsle())){
[356] 				return "No Island";
[357] 			}
[358] 			switch($session->getRank()){
[359] 				case SkyBlockSession::RANK_DEFAULT:
[360] 					return "Member";
[361] 				case SkyBlockSession::RANK_OFFICER:
[362] 					return "Officer";
[363] 				case SkyBlockSession::RANK_LEADER:
[364] 					return "Leader";
[365] 				case SkyBlockSession::RANK_FOUNDER:
[366] 					return "Founder";
[367] 			}
[368] 			return "No Rank";
[369] 		}else{

Backtrace:
#0 plugins/ScoreHud (3).phar/src/JackMD/ScoreHud/Main(246): JackMD\ScoreHud\data\DataManager->getIsleRank(pocketmine\Player object)
#1 plugins/ScoreHud (3).phar/src/JackMD/ScoreHud/Main(197): JackMD\ScoreHud\Main->process(pocketmine\Player object, string ..e... ..6..lServer)
#2 plugins/ScoreHud (3).phar/src/JackMD/ScoreHud/Main(179): JackMD\ScoreHud\Main->displayDefaultScoreboard(pocketmine\Player object)
#3 plugins/ScoreHud (3).phar/src/JackMD/ScoreHud/Main(147): JackMD\ScoreHud\Main->updateScore(pocketmine\Player object)
#4 plugins/ScoreHud (3).phar/src/JackMD/ScoreHud/task/ScoreUpdateTask(73): JackMD\ScoreHud\Main->addScore(pocketmine\Player object, string ..l..6Own..ea..6ge..9)
#5 src/pocketmine/scheduler/TaskHandler(159): JackMD\ScoreHud\task\ScoreUpdateTask->onRun(integer 361)
#6 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 361)
#7 src/pocketmine/plugin/PluginManager(688): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 361)
#8 src/pocketmine/Server(2549): pocketmine\plugin\PluginManager->tickSchedulers(integer 361)
#9 src/pocketmine/Server(2325): pocketmine\Server->tick()
#10 src/pocketmine/Server(2186): pocketmine\Server->tickProcessor()
#11 src/pocketmine/Server(1765): pocketmine\Server->start()
#12 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/multicraft/servers/server21/, string /home/minecraft/multicraft/servers/server21/plugins/)
#13 (1): require(string phar:///home/minecraft/multicraft/servers/server21/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by JackMD** [comment]
Ask me politely and I will look into it

**Comment by JackMD** [comment]
With that attitude I ain't doing shit

**Comment by JackMD** [comment]
So you can just fuck off if you want

**Comment by JackMD** [comment]
Also next time **@ManiakMCPE** do look at the dev builds on poggit and not just releases!

**Comment by JackMD** [comment]
Here I will make it easy for your laziness 
# ManiakMCPE

Here click this to download

https://poggit.pmmp.io/r/51786/ScoreHud_dev-27.phar

Now don't come after me if it nukes ur server!
