### ISSUE TITLE
Suggestion :D

### ISSUE THREAD

**Issue by LeoBdt** [JackMD/ScoreHud#105]
Hello can you support "RedSkyblock" ? https://poggit.pmmp.io/p/RedSkyBlock/3.0.3

**Comment by JackMD** [comment]
Please ask the plugins author to make an addon for ScoreHud

**Comment by LeoBdt** [comment]
Wdym ?

**Comment by JackMD** [comment]
I mean exactly what I said! I won't be adding support for any more plugin. You can ask the author of RedSkyBlock to make an addon for ScoreHud
