### ISSUE TITLE
Please make a addon Support for RedSkyBlock

### ISSUE THREAD

**Issue by GamerDaniel3000** [JackMD/ScoreHud#108]
Can you make a aupport for RedSkyBlock?
Liink: https://github.com/RedCraftGH/RedSkyBlock

**Comment by JackMD** [comment]
Please ask RedSkyBlock creator to make addon for ScoreHud. Starting from v5.0.0 onwards I will not be making/adding support for other people plugins. They can provide you with an addon. Make an issue on RedSkyBlock repo and ask the creator to add support for it.
