### ISSUE TITLE
Blank Line

### ISSUE THREAD

**Issue by NaniITzJerry** [JackMD/ScoreHud#110]
Blank Line Dont Show 
Blank Line Can show only 1
Ex : 
-> Name : Hi 
(blank)
-> Online : 1999
(blank)
-> www.example.net

**Comment by JackMD** [comment]
```php
- "Line One"
- " "
- "Line Three"
- "  "
- "Line Five"
- "   "
- "Line Seven"
- "    "
- "Line Nine"
```

If you can't see already. Then the thing is no two lines in score-lines can be same. So you have to space them out as shown

**Comment by Ifera** [comment]
This issue is now properly fixed. No need to add multiple line with spaces in them.
