### ISSUE TITLE
 Scoreboads are not displayed correctly

### ISSUE THREAD

**Issue by GamerDaniel3000** [JackMD/ScoreHud#113]
I have created a scoreboad for the world "lobby" and then I wanted to create different scoreboards in the scorehud.yml for different worlds but they are not displayed / updated correctly.

Config.yml: 
[config.zip](https://github.com/JackMD/ScoreHud/files/3116456/config.zip)

Scorehud.yml:
[scorehud.zip](https://github.com/JackMD/ScoreHud/files/3116459/scorehud.zip)

**Comment by JackMD** [comment]
Set `per-world-scoreboards` and `use-default-score-lines" to `true in `config.yml`
