### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by mikeygio10** [JackMD/ScoreHud#118]
i set it all up but then it dont show the stats it just shows the name of it like if i did 
- " Â§dUser: Â§5{name}"
why is it like that for all of them

**Comment by JackMD** [comment]
Read the readme on github. Use addons.

**Comment by mikeygio10** [comment]
i did your link to download does not work i found this page but it did not work

**Comment by mikeygio10** [comment]
https://github.com/JackMD/ScoreHud-Addons
