### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jhampt** [JackMD/ScoreHud#121]
public function addBreaks(Player $player, $breaks){
        $current = $this->getStats($player)["breaks"];
        $this->getStats($player)->set("breaks", $current + $breaks);
        $this->saveStats($player);
    }
    
    public function addPlaces(Player $player, $places){
        $current = $this->getStats($player)["places"];
        $this->getStats($player)->set("places", $current + $places);
        $this->saveStats($player);
    }
    
    public function onBreak(BlockBreakEvent $event){
        if($this->config->get("breaks") == "true"){
            $this->enderStats()->addBreaks($event->getPlayer(), 1);
        }
    }
use the following and add support for broken blocks and placed or you do you want me to do it and make pull request???

**Comment by JackMD** [comment]
Refer to wiki. Make an addon and submit it over to ScoreHud-Addons repo.
