### ISSUE TITLE
 Turn scoreboards off completely in certain worlds

### ISSUE THREAD

**Issue by GamerDaniel3000** [JackMD/ScoreHud#125]
Hey, add a feature that allows you to completely remove them in certain world scoreboards

**Comment by JackMD** [comment]
https://github.com/JackMD/ScoreHud/blob/749162dfc77369c25cb2feb7c40a691af454781c/resources/config.yml#L34-L40

https://github.com/JackMD/ScoreHud/blob/749162dfc77369c25cb2feb7c40a691af454781c/resources/scorehud.yml#L21-L24


If only you had read...

**Comment by GamerDaniel3000** [comment]
@JackMD ....
https://workupload.com/file/udcugGyP
