### ISSUE TITLE
Per-World Scoreboards not working

### ISSUE THREAD

**Issue by ItsMeBman** [JackMD/ScoreHud#127]
I am very confused on how to disable scoreboards in certain worlds. Before you instantly close this, I have read readme and turned per-world scoreboard to true. I am having issues enabling the scoreboard in my hub. I have configured with scoreboard.yml and config.yml but nothing works. I would like the scoreboard to only show in my lobbies. 
![IMG_0953](https://user-images.githubusercontent.com/51290819/59057330-71f91080-889a-11e9-848c-55d76bddf7bb.jpeg)
![IMG_0954](https://user-images.githubusercontent.com/51290819/59057340-78878800-889a-11e9-835d-8d8503950591.jpeg)

**Comment by ItsMeBman** [comment]
My world is called spawn

**Comment by JackMD** [comment]
Tested and working fine. Somethings wrong on your end.
