### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by AirLinesCraft** [JackMD/ScoreHud#129]
So, I've downloaded the addons, extracted the zip file, and put them in the correct folder (plugin_data/ScoreHud/addons), all with the server offline. However when I'm in game i still see the brackets (eg. {name} , {rank} ).

**Comment by JackMD** [comment]
Can you show your addons folder?

**Comment by AirLinesCraft** [comment]
Here it is: https://imgur.com/a/LOOEoFS

**Comment by JackMD** [comment]
Looks okay. Are you sure the plugin is enabled or not? Also any errors on console?

**Comment by AirLinesCraft** [comment]
the only error i get about the plugin in the console is
 [ScoreHud] Update notify error: Could not resolve host: poggit.pmmp.io

**Comment by JackMD** [comment]
Well that can be ignored. That occurs since your internet connection is bad etc. Also in the console does it show the addons enabled? Send a screenshot of it showing something along these lines `Addon addon_name enabled`.

**Comment by AirLinesCraft** [comment]
it doesn't show anything about addons on console.

**Comment by JackMD** [comment]
is the plugin enabled or not?

**Comment by LoKisethegamer** [comment]
I have the same probleme

**Comment by JackMD** [comment]
Both of you show your scorehud.yml file.

**Comment by BlueWhaleYT** [comment]
I'm also meet this issue
