### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LoKisethegamer** [JackMD/ScoreHud#131]
Hi, I downloaded ScoreHUD and it works perfectly.  So I downloaded BasicAddon for use {ping} etc ... But they do not work while BasicAddon is in PocketMine / plugin_data / scoreHud / addons.
I don't know what I can do.

**Comment by JackMD** [comment]
Paste your scorehud.yml file.

**Comment by LoKisethegamer** [comment]
---
# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
scorehud-version: 1

# Changing titles of the scoreboard.
# Can be of any number.
server-names:
- "§l§aPola §dServ"
- "§l§bPola §cServ"
- "§l§cPola §bServ"
- "§l§dPola §aServ"

# Note: You can find links to the required/supported plugins via the README.md.
# IMPORTANT NOTE: You can only set a maximum of 15 lines and no more.
#
# You can edit the lines already set below and adjust them according to your needs.
#
# If you want same scoreboard to be displayed in every world then set per-world-scoreboard to false in config.yml.
#
# If you have per-world-scoreboard enabled and want to display a default scoreboard for a world you didn't mention
# in scoreboards key below then set use-default-score-lines to true in config.yml.
#
# After that edit the following score-lines to edit the scoreboard.
#
# You need to add addons for adding support for tags.
# If you want support for a plugin please ask the plugin author of that plugin to add support for ScoreHud by making an addon.
#
# For a list of addons go here https://github.com/JackMD/ScoreHud/blob/master/README.md#addons.
score-lines:
- " §bOnline: §a{online} §c/ §d{max_online} "
- " §dTPS: §5{tps} "
- " §cPing §6{ping} "
- " §2X: §4{X} §2Y: §4{Y} §2Z: §4{Z}"
# If you want to display different scoreboards for every world then set per-world-scoreboard to true in config.yml.
# After that edit the following to suit your needs.
scoreboards:
# EXAMPLE CONFIGURATION:
# -------------------
# "world name":     | The name of the world. Enclose it in inverted commas.
#   lines:          | This key is important. And the plugin won't function without it.
#   - " Line #1"    | Line number one. You can use any of the above tags.
#   - " Line #2"    | You can add a maximum of 15 lines.
#--------------------
  "world":
    lines:
    - " §dName: §5{name}"
    - " §bOnline: §a{online} §c/ §d{max_online}"
  "world 2":
    lines:
    - " §dTPS: §5{tps}"
    - " §bLoad: §a{load}"
...

**Comment by JackMD** [comment]
Can you upload a screenshot of your addons folder?

**Comment by JackMD** [comment]
This looks okay. Also check on console if there are any errors. Also check for a line saying `addon_name successfully enabled.` is there any such message? I have double checked it. Working fine for me. What os are you running this on? Linux or windows? Or are you using a host? If using a host then do send their address.

**Comment by LoKisethegamer** [comment]
For addons I have only BasicAddon.php and README.txt

**Comment by LoKisethegamer** [comment]
The console doesn't show me anything about the addon. I on mobile (Samsung) and I use PocketMine-MP

**Comment by JackMD** [comment]
First of all you shouldn't be running the server on your phone. Secondly I cba to fix it (provided if broken) on android etc. Its working fine on linux and windows.

**Comment by LoKisethegamer** [comment]
Ok
