### ISSUE TITLE
Scorehud.yml

### ISSUE THREAD

**Issue by LoganMontgomery** [JackMD/ScoreHud#135]
I cant seem to make variables work, for example if I do "Name: {name}" it just says Name: {name} in the scoreboard! I am fairly new to this so I don't know what I am doing. And please don't say read the readme, I have no clue what it means on this topic!

**Comment by Iust1n** [comment]
Yeah it is happening me too, but i think u need addon for this!

**Comment by Shaggy0815** [comment]
Download to your addons folder the BasicAddon.php and any other addon you need.  [here](https://github.com/JackMD/ScoreHud-Addons/blob/master/BasicAddon.php)
After that you can use {name}

**Comment by LoganMontgomery** [comment]
Oh, ok thank you, I just looked yesterday and I still couldn’t figure it out. That seemed to fix my problem.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NixonBlaze45** [comment]
Plugin doesn't work lmao I'm so confused

**Comment by Shaggy0815** [comment]
Download to your addons folder the BasicAddon.php and any other addon you need.

**Comment by NixonBlaze45** [comment]
Shaggy I Downloaded all of the required add-ons and plugin, after I edited the config and scorehud.yml file I input this
- " name: {name}"
- " rank: {rank}"
- "money: {money}" 
But in-game it literally shows like that, I enabled per world-scoreboards
So if u think you could help me make a video on YouTube or Add me in discord
NixonBlaze#0302
