### ISSUE TITLE
Disable ScoreHud

### ISSUE THREAD

**Issue by KingRainbow44** [JackMD/ScoreHud#137]
Is it possible to disable scorehud in worlds we choose? I have a skywars plugin and ScoreHud is interfering with its scoreboard.

**Comment by JackMD** [comment]
Duplicate of #125 and #26

**Comment by KingRainbow44** [comment]
No, not like that. I mean, like COMPLETELY. Not just showing a blank ScoreHud. If you need a video explanation on what I mean, then please respond to this.
