### ISSUE TITLE
Addon.

### ISSUE THREAD

**Issue by sobbingsmcpe** [JackMD/ScoreHud#139]
I am trying to make a Addon for a plugin im using, xDuels. But i tried adding {queues} and {fights} but whenever i run it, it only gets into the Loader aka the Main file. How do i change this? Thanks

**Comment by JackMD** [comment]
Paste the addon that you made on gist and link it here.

**Comment by sobbingsmcpe** [comment]
<?php
declare(strict_types = 1);

/**
 * @name xDuelsAddon
 * @version 1.0.0
 * @main JackMD\ScoreHud\Addons\xDuelsAddon
 * @depend xDuels
 */

namespace JackMD\ScoreHud\Addons
{

    use JackMD\ScoreHud\addon\AddonBase;
    use CortexPE\xDuels\command\DuelCommand;
    use CortexPE\xDuels\command;
    use pocketmine\Player;

    class xDuelsAddon extends AddonBase{

        /** @var xDuels */
        private $xduels;

        public function onEnable(): void{
            $this->xduels = $this->getServer()->getPluginManager()->getPlugin("xDuels");
        }

        /**
         * @param Player $player
         * @return array
         */
        public function getProcessedTags(Player $player): array{
            return [
                "{queue}" => $this->xduels->getQueueCount(),
                "{fights}" => $this->xduels->getMatchCount()
            ];
        }
    }
}

**Comment by sobbingsmcpe** [comment]
[xDuelsAddon.zip](https://github.com/JackMD/ScoreHud/files/3861197/xDuelsAddon.zip)

**Comment by JackMD** [comment]
uh that looks fine are you sure that the addon is loading?

**Comment by sobbingsmcpe** [comment]
The addon is loading, but it only goes inside of the Loader.php and the coding for the queue is in the DuelCommand.php. in xDuels\commands. Any reaosn?

**Comment by JackMD** [comment]
are you using it on android or any other phone?

**Comment by JackMD** [comment]
Also
are the queue and fights tags displayed on the scoreboard or no?

**Comment by sobbingsmcpe** [comment]
for the scoreboard, it has In fights: {fights} and In Queues: {queues} and i am using it on PC.

**Comment by JackMD** [comment]
Something wrong at your end. plugin is working just fine
