### ISSUE TITLE
[Suggestion] Add blocks placed and broken

### ISSUE THREAD

**Issue by FazeHamptonApex** [JackMD/ScoreHud#16]

**Comment by JackMD** [comment]
For skyblock?

**Comment by FazeHamptonApex** [comment]
No

**Comment by JackMD** [comment]
Ahh well... I cannot implement it directly into this plugin. Do you know of any other pligin that counts the blocks you have placed or broken?

**Comment by FazeHamptonApex** [comment]
Check ProfileUD BY INFENUS101 I belive that is

**Comment by FazeHamptonApex** [comment]
okay i will send it now

**Comment by FazeHamptonApex** [comment]
https://github.com/Infernus101/ProfileUI/tree/master/

**Comment by FazeHamptonApex** [comment]
here https://github.com/Infernus101/ProfileUI/tree/master/

**Comment by jhampt** [comment]
when this will be implemented?

**Comment by JackMD** [comment]
Please ask the plugins author to make an addon for ScoreHud
