### ISSUE TITLE
[Suggestion] Per world Scoreboards?

### ISSUE THREAD

**Issue by AlexPads** [JackMD/ScoreHud#18]
Could there be a way to make a Different Scoreboard per the world that the player is in? 
Like when they are in the hub the board has
Title
name 
money
things like that and when fo say they are in a Skyblock world using the skyblock plugin by quartz guy scince all the worlds start with "Is" there could be a board set to work when the world starts with "is"  there could be 
name
money
island sized
blocks 
etc...

You think this could be possible?
i can help you test it on my server if you need :) you know my discord!
ok, hope to hear from you soon!

**Comment by JackMD** [comment]
Your request is complete.
