### ISSUE TITLE
Kills and deaths

### ISSUE THREAD

**Issue by OmarEnder** [JackMD/ScoreHud#2]
HI, can u add more features like {kills} and {deaths}

**Comment by JackMD** [comment]
Hmm okay i will look into it

**Comment by xXNiceYT** [comment]
@OmarEnder what plugin u want him to use

**Comment by OmarEnder** [comment]
@xXNiceYT killChat

**Comment by JackMD** [comment]
Nah Im making a new plugin for registering player deaths and etc

**Comment by JackMD** [comment]
There it is, You will need KDR plugin for adding {kills}, {deaths} and {kdr} where {kdr} is the kill to death ratio
