### ISSUE TITLE
[Suggestion] Add player rank %

### ISSUE THREAD

**Issue by AlexPads** [JackMD/ScoreHud#20]
Could you add a Rank percentage of how close the person is to doing /rankup?

like if the rank is 4000$ and they have 1000$ they are 25% of the way there? 

Thanks would be a great help :)

**Comment by JackMD** [comment]
Alright will try to implement when I get time

**Comment by AlexPads** [comment]
Alrighty! Thanks!

**Comment by JackMD** [comment]
Your request is complete

**Comment by AlexPads** [comment]
Thank you so much will report bug or anything like that 😁

**Comment by JackMD** [comment]
Just so you know, I am currently working on adding support for per world scoreboards
