### ISSUE TITLE
Custom variables support

### ISSUE THREAD

**Issue by and7ey** [JackMD/ScoreHud#213]
Hello, is there any way to display custom variable with ScoreHud?

Let's say I would like to

1) create custom `$var` and display its content with ScoreHud? I.e. `$var = "Some custom text"`, ScoreHud displays "Some custom text", then I update `$var` thru console with some other content "Some other text", ScoreHuds displays updated text.

2) the same but with integer content of `$var`.

**Comment by Ifera** [comment]
Please take a look here.
https://github.com/Ifera/ScoreHud/wiki/%5Bv6%5D-Tag-Handling-(LATEST)
