### ISSUE TITLE
Could you Make a Special Permission Only Scoreboard?

### ISSUE THREAD

**Issue by AlexPads** [JackMD/ScoreHud#28]
Just With the same Things Per world But Have an admin one Like if they have boards.admin or something of your liking then in this world it shows this or that and if not labeled it shows this but with admins so.

worlds:
  "LOBBY"
  Admin: true/False
     - "Whatever"
  "World"
  Admin: true false and You could make 2 boards with slight variations for each world with or without permissions! 

Thank you This is NOT and urgent Request and i don't expect this Quickly So take your Time 😂

Sincerely
     ~ Pixel (saltypixel.ga)

**Comment by JackMD** [comment]
I'm not willing to implement it. Not now. And modt probably not in the future.
