### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SuperAdam47** [JackMD/ScoreHud#31]
Add per PurePerms group scoreboard

**Comment by JackMD** [comment]
Uh what does that even mean?

**Comment by SuperAdam47** [comment]
Guest Group ScoreBoard:

- " §dName: §5{name}"
- " §bOnline: §a{online} §c/ §d{max_online}"
- " §dRank: §5{prison_rank}"
- " §2Money: §f{money}§2$"
- " §cKills: §f{kills}"
Admin Scoreboard:
- " §dName: §5{name}"
- " §bOnline: §a{online} §c/ §d{max_online}"
- " §dRank: §5{prison_rank}"
- " §6St-Rank: §r{rank}"
- " §2Money: §f{money}§2$"
- " §cKills: §f{kills}"

**Comment by JackMD** [comment]
No need for that. Just use {rank} and the plugin would show your rank either admin, guest or whatever.
