### ISSUE TITLE
Pls Fix

### ISSUE THREAD

**Issue by s3bastianeljas** [JackMD/ScoreHud#35]
Console says:

[14:17:39] [Server thread/CRITICAL]: ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "plugins/ScoreHud.phar/src/JackMD/ScoreHud/Main" at line 85"

**Comment by NicolassMD** [comment]
Why If i write in config - " §aName: §d{name}" IT doesn't show my name and also no one grom {name,rank,ping,etc} doesn't work pls fix 

Sorry for my bad English!

**Comment by JackMD** [comment]
Read the readme here on github. Use addons.

**Comment by NicolassMD** [comment]
how do I add these addonus to the plugin

**Comment by HIOK3RV** [comment]
NicolassMD 
commented about 1 month ago
Why If i write in config - " §aName: §d{name}" IT doesn't show my name

**Comment by HIOK3RV** [comment]
Why If i write in config - " §aName: §d{name}" IT doesn't show my name
