### ISSUE TITLE
Suggestion+

### ISSUE THREAD

**Issue by SuperAdam47** [JackMD/ScoreHud#37]
Add per group scoreboard:

Guest Group ScoreBoard:

- " §dName: §5{name}"
- " §bOnline: §a{online} §c/ §d{max_online}"
- " §dRank: §5{prison_rank}"
- " §2Money: §f{money}§2$"
- " §cKills: §f{kills}"

Admin Group Scoreboard:

- " §dName: §5{name}"
- " §bOnline: §a{online} §c/ §d{max_online}"
- " §dRank: §5{prison_rank}"
- " §fServer Load: {load}"
- " §6Level: §r{level_name}"
- " §6Item: §r{item_id}:{item_meta}:{item_count}"

**Comment by JackMD** [comment]
Sorry but I am not willing to put any further work into this plugin.
