### ISSUE TITLE
Title bug

### ISSUE THREAD

**Issue by VaeNetwork** [JackMD/ScoreHud#4]
You put the Line title
```
server-names:
- "§l§aServer §dName"
- "§l§bServer §cName"
- "§l§cServer §bName"
- "§l§dServer §aName"
```
But the In game title doesn't change from A to B, but the one below changes

So what is the function
This code
```
update-interval: 3
```

**Comment by VaeNetwork** [comment]
. . . ?

**Comment by JackMD** [comment]
I will be fixing it later.

**Comment by mikemike17347** [comment]
And the other lines are not there

**Comment by mikemike17347** [comment]
The format it default and it's still not showing

**Comment by JackMD** [comment]
@mikemike17347 everything is working good. Make sure you are using the plugin in .phar form from poggit

**Comment by JackMD** [comment]
This issue is now fixed
