### ISSUE TITLE
Suggestion {CPS}?

### ISSUE THREAD

**Issue by AlexPads** [JackMD/ScoreHud#5]
Could you possibly add a ClickperSecond counter i have seen it on some other servers and wondered how hard it would be for you to add it? Thankyou!!

**Comment by JackMD** [comment]
Hmm I really don't think it would be a good to add it directly into the plugin itself. I might make a plugin that counts the player clicks and then add support for it into this one

**Comment by AlexPads** [comment]
Alright sounds great
:)

**Comment by JackMD** [comment]
It was late but hey the feature is added now. Enjoy!!

**Comment by AlexPads** [comment]
Thankyou!
