### ISSUE TITLE
DOESNT WORK

### ISSUE THREAD

**Issue by MikeyHampton** [JackMD/ScoreHud#9]
19.11 02:45:36 [Multicraft] MikeyHampton[/151.213.85.247:56844] ran command Message of the Day
19.11 02:45:38 [Server] Server thread/CRITICAL Could not execute task JackMD\ScoreHud\task\ScoreUpdateTask: Class 'JackMD\ScoreFactory\ScoreFactory' not found
19.11 02:45:38 [Server] Server thread/CRITICAL Error: "Class 'JackMD\ScoreFactory\ScoreFactory' not found" (EXCEPTION) in "ScoreHud-master/src/JackMD/ScoreHud/Main" at line 79
19.11 02:45:38 [Server] Server thread/DEBUG #0 ScoreHud-master/src/JackMD/ScoreHud/task/ScoreUpdateTask(66): JackMD\ScoreHud\Main->addScore(pocketmine\Player object, string ..l..cServer ..bName)
19.11 02:45:38 [Server] Server thread/DEBUG #1 src/pocketmine/scheduler/TaskHandler(159): JackMD\ScoreHud\task\ScoreUpdateTask->onRun(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/TaskScheduler(203): pocketmine\scheduler\TaskHandler->run(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(669): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2512): pocketmine\plugin\PluginManager->tickSchedulers(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2265): pocketmine\Server->tick()
19.11 02:45:38 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2135): pocketmine\Server->tickProcessor()
19.11 02:45:38 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1701): pocketmine\Server->start()
19.11 02:45:38 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
19.11 02:45:38 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
19.11 02:45:38 [Server] Server thread/INFO MikeyHampton joined the game

**Comment by MikeyHampton** [comment]
19.11 02:45:36 [Multicraft] MikeyHampton[/151.213.85.247:56844] ran command Message of the Day
19.11 02:45:38 [Server] Server thread/CRITICAL Could not execute task JackMD\ScoreHud\task\ScoreUpdateTask: Class 'JackMD\ScoreFactory\ScoreFactory' not found
19.11 02:45:38 [Server] Server thread/CRITICAL Error: "Class 'JackMD\ScoreFactory\ScoreFactory' not found" (EXCEPTION) in "ScoreHud-master/src/JackMD/ScoreHud/Main" at line 79
19.11 02:45:38 [Server] Server thread/DEBUG #0 ScoreHud-master/src/JackMD/ScoreHud/task/ScoreUpdateTask(66): JackMD\ScoreHud\Main->addScore(pocketmine\Player object, string ..l..cServer ..bName)
19.11 02:45:38 [Server] Server thread/DEBUG #1 src/pocketmine/scheduler/TaskHandler(159): JackMD\ScoreHud\task\ScoreUpdateTask->onRun(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/TaskScheduler(203): pocketmine\scheduler\TaskHandler->run(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(669): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2512): pocketmine\plugin\PluginManager->tickSchedulers(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2265): pocketmine\Server->tick()
19.11 02:45:38 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2135): pocketmine\Server->tickProcessor()
19.11 02:45:38 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1701): pocketmine\Server->start()
19.11 02:45:38 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
19.11 02:45:38 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
19.11 02:45:38 [Server] Server thread/INFO MikeyHampton joined the game

**Comment by MikeyHampton** [comment]
19.11 02:45:36 [Multicraft] MikeyHampton[/151.213.85.247:56844] ran command Message of the Day
19.11 02:45:38 [Server] Server thread/CRITICAL Could not execute task JackMD\ScoreHud\task\ScoreUpdateTask: Class 'JackMD\ScoreFactory\ScoreFactory' not found
19.11 02:45:38 [Server] Server thread/CRITICAL Error: "Class 'JackMD\ScoreFactory\ScoreFactory' not found" (EXCEPTION) in "ScoreHud-master/src/JackMD/ScoreHud/Main" at line 79
19.11 02:45:38 [Server] Server thread/DEBUG #0 ScoreHud-master/src/JackMD/ScoreHud/task/ScoreUpdateTask(66): JackMD\ScoreHud\Main->addScore(pocketmine\Player object, string ..l..cServer ..bName)
19.11 02:45:38 [Server] Server thread/DEBUG #1 src/pocketmine/scheduler/TaskHandler(159): JackMD\ScoreHud\task\ScoreUpdateTask->onRun(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/TaskScheduler(203): pocketmine\scheduler\TaskHandler->run(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(669): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2512): pocketmine\plugin\PluginManager->tickSchedulers(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2265): pocketmine\Server->tick()
19.11 02:45:38 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2135): pocketmine\Server->tickProcessor()
19.11 02:45:38 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1701): pocketmine\Server->start()
19.11 02:45:38 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
19.11 02:45:38 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
19.11 02:45:38 [Server] Server thread/INFO MikeyHampton joined the game

**Comment by MikeyHampton** [comment]
19.11 02:45:36 [Multicraft] MikeyHampton[/151.213.85.247:56844] ran command Message of the Day
19.11 02:45:38 [Server] Server thread/CRITICAL Could not execute task JackMD\ScoreHud\task\ScoreUpdateTask: Class 'JackMD\ScoreFactory\ScoreFactory' not found
19.11 02:45:38 [Server] Server thread/CRITICAL Error: "Class 'JackMD\ScoreFactory\ScoreFactory' not found" (EXCEPTION) in "ScoreHud-master/src/JackMD/ScoreHud/Main" at line 79
19.11 02:45:38 [Server] Server thread/DEBUG #0 ScoreHud-master/src/JackMD/ScoreHud/task/ScoreUpdateTask(66): JackMD\ScoreHud\Main->addScore(pocketmine\Player object, string ..l..cServer ..bName)
19.11 02:45:38 [Server] Server thread/DEBUG #1 src/pocketmine/scheduler/TaskHandler(159): JackMD\ScoreHud\task\ScoreUpdateTask->onRun(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/TaskScheduler(203): pocketmine\scheduler\TaskHandler->run(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(669): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2512): pocketmine\plugin\PluginManager->tickSchedulers(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2265): pocketmine\Server->tick()
19.11 02:45:38 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2135): pocketmine\Server->tickProcessor()
19.11 02:45:38 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1701): pocketmine\Server->start()
19.11 02:45:38 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
19.11 02:45:38 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
19.11 02:45:38 [Server] Server thread/INFO MikeyHampton joined the game

**Comment by MikeyHampton** [comment]
19.11 02:45:36 [Multicraft] MikeyHampton[/151.213.85.247:56844] ran command Message of the Day
19.11 02:45:38 [Server] Server thread/CRITICAL Could not execute task JackMD\ScoreHud\task\ScoreUpdateTask: Class 'JackMD\ScoreFactory\ScoreFactory' not found
19.11 02:45:38 [Server] Server thread/CRITICAL Error: "Class 'JackMD\ScoreFactory\ScoreFactory' not found" (EXCEPTION) in "ScoreHud-master/src/JackMD/ScoreHud/Main" at line 79
19.11 02:45:38 [Server] Server thread/DEBUG #0 ScoreHud-master/src/JackMD/ScoreHud/task/ScoreUpdateTask(66): JackMD\ScoreHud\Main->addScore(pocketmine\Player object, string ..l..cServer ..bName)
19.11 02:45:38 [Server] Server thread/DEBUG #1 src/pocketmine/scheduler/TaskHandler(159): JackMD\ScoreHud\task\ScoreUpdateTask->onRun(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/TaskScheduler(203): pocketmine\scheduler\TaskHandler->run(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(669): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2512): pocketmine\plugin\PluginManager->tickSchedulers(integer 1321)
19.11 02:45:38 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2265): pocketmine\Server->tick()
19.11 02:45:38 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2135): pocketmine\Server->tickProcessor()
19.11 02:45:38 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1701): pocketmine\Server->start()
19.11 02:45:38 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
19.11 02:45:38 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
19.11 02:45:38 [Server] Server thread/INFO MikeyHampton joined the game

**Comment by JackMD** [comment]
Did you read the errors? Anyway yous the plugin phar from poggit. Don't use the source code
